### ISSUE TITLE
Evernotesession not found

### ISSUE THREAD

**Issue by hermanccw** [Evernote/evernote-sdk-ios#11]
Getting this error.  

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_EvernoteSession"

The set up I have is that I created a submodule in under my project folder, so evernote lives in Project_dir/Submodules/evernote

In my header search path, I set it to be "${SOURCE_ROOT}/Submodules/evernote/evernote-sdk-ios"

Am I doing something wrong?

**Comment by mcglincy** [comment]
How are you currently including the source code?  If you're directly adding them to your xcode proj, are the various Evernote source files properly added to Compile Sources build phase of your target?

**Comment by hermanccw** [comment]
it probably wasn't, but I fixed it by using cocoapods and it's working now.  Although there was a little problem on the cocoapods side with some name conflicts.  For example, there was a file call NSDate+Base64 that I had to remove from evernote since it was giving me duplicate symbols error.  May I suggest using EN as a previous for common classes like these to get rid of duplicate symbol problem.  closing this. thx

**Comment by mcglincy** [comment]
Also, if you want to put your code up on a public github repo, I'd be happy to help get it to build.

**Comment by mcglincy** [comment]
OK, great. 

btw, we're working on a new source update that fixes several bugs and uses a new authentication call signature.  I'm going to bump the cocoapods version once we get that submitted, likely this week.

**Comment by hermanccw** [comment]
alright, I'll watch you guys on github for so I can get the update.

On Wed, Jun 13, 2012 at 4:13 PM, Matt McGlincy <
reply@reply.github.com
