### ISSUE TITLE
name conflict on GCOAuth.h  and NSData_Base64.h

### ISSUE THREAD

**Issue by hermanccw** [Evernote/evernote-sdk-ios#13]
Hi there,

I get a name conflict at GCOAuth.h and NSData_Base64.h when using the sdk, maybe you can prefix it with EN to avoid name collision?

**Comment by mave99a** [comment]
I got this issue too when link with RestKit since they all include the same 3rd party libs. So far I just remove the duplicated one from one library but I am looking for better solutions.

**Comment by mustafa** [comment]
Thanks, fixed in 1.0.0
