### ISSUE TITLE
no update on cocoa pods

### ISSUE THREAD

**Issue by iainsmith** [Evernote/evernote-sdk-ios#14]
Hi

It would be great to be able to update our work via cocoa pods. I tried pointing to this github but only got:

Updating spec repo `master'
- Pre-downloading: `Evernote-SDK-iOS'
  No podspec exists at path`/Users/Iain/Xcode projects/EvernoteDone/Pods/Evernote-SDK-iOS/Evernote-SDK-iOS.podspec'.

**Comment by mustafa** [comment]
Evernote-SDK-iOS pod has been updated to 1.0.1
