### ISSUE TITLE
Allow showing a some loading indicator

### ISSUE THREAD

**Issue by tomquist** [Evernote/evernote-sdk-ios#16]
The new authentication system (using a view controller instead of opening the external browser) in `EvernoteSession` doesn't currently allow to show a loading indicator when authentication is started. To be explicit, we need some way to get informed when the temp-token is fetched to hide a previously displayed activity indicator. Here are a couple of techniques to do things like that in Objective-C:
- Allow adding a delegate to `EvernoteSession`
- Publish a `NSNotification` using the `NSNotificationCenter`
- Add another callback-block in `authenticateWithViewController:completionHandler:` (Callback-Blocks are usually not used for things like that (because they retain everything used in it for a potentially long time), they are a bit misused in the evernote-sdk)

**Comment by mustafa** [comment]
We have a completion block that you can use to hide any activity indicator.

**Comment by tomquist** [comment]
The completion block is called AFTER the authentication view has been shown and authentication is finished. However, we need a callback before the view is shown so that we can hide an activity indicator (which may overlay the authentication view) when the temp-token is loaded and the authentication view is about to be shown.

**Comment by mustafa** [comment]
You should instead make sure that your activity indicator does not overlay the authentication view. We will add an example for this in the sample app for the upcoming release.

**Comment by tomquist** [comment]
Still this is not ideal. Why should one change the behavior of the activity indicator (which is possibly used in many other places). In this scenario the SDK claims to do something (which is indicated by some activity indicator) when it actually does nothing and waits for user input (when it shows the authentication view). This clearly is a conceptual error.
