### ISSUE TITLE
compile warnings in thrift/transport

### ISSUE THREAD

**Issue by VilemKurz** [Evernote/evernote-sdk-ios#20]
There are four of them - see the screenshots. Could you get rid of them?
<img src="http://img269.imageshack.us/img269/6035/evernoteincompatibledel.png" alt="Image Hosted by ImageShack.us"/>
<img src="http://img805.imageshack.us/img805/7546/evernoteconflictingpara.png" alt="Image Hosted by ImageShack.us"/>

**Comment by sethhitch** [comment]
Resolved in 0.1.4.
