### ISSUE TITLE
minor - webview loading indicator

### ISSUE THREAD

**Issue by VilemKurz** [Evernote/evernote-sdk-ios#21]
It is not urgent, but it would enhance user experience, if there was some indicator of network communication during loading authorisation web view. Something like this (after clicking on "prihlasit sa" (login) authorisation starts, and UIActivityIndicatorView in upper right corner starts to spin)
<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/163/evernoteactivityindicat.png/'><img src='http://img163.imageshack.us/img163/2411/evernoteactivityindicat.png' border='0'/></a><br>Uploaded with <a target='_blank' href='http://imageshack.us'>ImageShack.us</a>

**Comment by mustafa** [comment]
Added in 0.2.2.
