### ISSUE TITLE
TSocketServer.m references import of TNSFileHandleTransport.h

### ISSUE THREAD

**Issue by chriscox** [Evernote/evernote-sdk-ios#22]
There is a build error with v0.1.4 with the 3rdParty thrift classes.

File TSocketServer.m references TNSFileHandleTransport.h which has been subsequently removed in this version.

See line #22:
# import "TNSFileHandleTransport.h"

**Comment by sethhitch** [comment]
Fixed in version 0.1.5 by removing the unused Thrift/server package. SHA: 618b82b06717e7008849083253071982e6ef7e2e
