### ISSUE TITLE
Double tap on a button will crash the web login form

### ISSUE THREAD

**Issue by susieyy** [Evernote/evernote-sdk-ios#23]
Sometime, The Auth Web browser to crash while sending a request, when you tap the Sign in or the Authorize button again to tap the button.
We use Evernote SDK ver 0.1.5 and iOS SDK ver 5.1.0.

![](https://img.skitch.com/20120718-r3swwyudce934wt3yu3q4ereq.jpg)
![](https://img.skitch.com/20120718-kygmnb53dt3imptmytw42qfgx7.jpg)

![](https://img.skitch.com/20120718-qg39f19g91upt5w3hqerpw3ami.jpg)

**Comment by mustafa** [comment]
Not able to repro this. Please provide more info.
