### ISSUE TITLE
authenticated user notebook lookup failure

### ISSUE THREAD

**Issue by drunknbass** [Evernote/evernote-sdk-ios#24]
Not sure the problem, but after a fresh auth i can fetch notebooks, etc just fine. After a little time passes and i run the app it will authenticate but notebook/note/etc lookups all fail (error 9).
Looking at the token it is there and not nil, so im not really sure why my lookups start to fail and dont see any exposed methods other than completely logging out and back in to fix.

**Comment by sethhitch** [comment]
Error 9 is "auth expired". What's your API consumer key (not the secret)? I'll check the expected validity period of your tokens.

**Comment by drunknbass** [comment]
noenotes

**Comment by sethhitch** [comment]
For some reason your key was configured to create 1-hour tokens. I modified it so that newly issued tokens will be valid for a year.

**Comment by drunknbass** [comment]
YES! thank you.

http://25.media.tumblr.com/tumblr_m4lm1fC9km1rv6skio1_400.gif
