### ISSUE TITLE
warning when using Apple LLVM 4.0 compiler

### ISSUE THREAD

**Issue by VilemKurz** [Evernote/evernote-sdk-ios#25]
see the screenshot. Would be handy, if you get rid of it, so that everybody can use your sdk without customisations.

<a target='_blank' title='ImageShack - Image And Video Hosting' href='http://imageshack.us/photo/my-images/827/evernotewarning.png/'><img src='http://img827.imageshack.us/img827/5176/evernotewarning.png' border='0'/></a>

**Comment by sbl** [comment]
see 841c9d4a67bc2d987cc317b00ccf4d05830b8701

**Comment by VilemKurz** [comment]
thank you
