### ISSUE TITLE
incorrect username and/or password 

### ISSUE THREAD

**Issue by MoathOthman** [Evernote/evernote-sdk-ios#30]
i am using the sample app for ios device 

after putting my CONSUMER_KEY and CONSUMER_SECRET 
    NSString *EVERNOTE_HOST = @"sandbox.evernote.com";

NSString *CONSUMER_KEY = @"moathothmanaliwat";
    NSString *CONSUMER_SECRET = @"efd4e31c335c9f8f";

then tap o authentication button ...
interring username and password ..correct one of my account on evernote 

i get  that message ...incorrect username and/or password 
what do i need to do ?!
first time i use evernote sdk ...

thank you

**Comment by emreberge** [comment]
"interring username and password ..correct one of my account on evernote"

You need a sandboxed account with sanboxed app.

**Comment by MoathOthman** [comment]
oh yah thank you ..
