### ISSUE TITLE
+[ENCredentialStore load] conflicts with +[NSObject load]

### ISSUE THREAD

**Issue by davedelong** [Evernote/evernote-sdk-ios#34]
[`+load` is a method defined by `NSObject`](http://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSObject_Class/Reference/Reference.html#//apple_ref/doc/uid/20000050-load) that is run when a class or category is loaded by the Objective-C runtime.

However, `ENCredentialStore` has overridden this method to unarchive the credentials stored in `NSUserDefaults`.

**Comment by mustafa** [comment]
Thanks. Fixed in the latest commit.
