### ISSUE TITLE
iOS SDK does not appear to support authentication with a Developer Token

### ISSUE THREAD

**Issue by davedelong** [Evernote/evernote-sdk-ios#35]
According to the [Evernote Documentation](http://dev.evernote.com/documentation/cloud/chapters/Authentication.php#devtoken), developers can request a Developer Token for accessing their personal Evernote account.

There does not appear to be a way in the iOS SDK to utilize this ability.

**Comment by sethhitch** [comment]
That's correct. Developer tokens are intended to (a) make it easy to quickly try out the API without needing to implement OAuth, and (b) write code that will only ever access your own personal Evernote account. Our iOS SDK makes implementing OAuth trivial, and it seems pretty unlikely that you'd write an iOS app just to access your own account, so we didn't add the complexity of supporting developer tokens.
