### ISSUE TITLE
-[__NSArrayM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0xd197fe0

### ISSUE THREAD

**Issue by siuying** [Evernote/evernote-sdk-ios#36]
Using iOS 5.1. when using the new API, my app always crashed at (https://github.com/evernote/evernote-sdk-ios/blob/master/evernote-sdk-ios/EvernoteSession.m#L320. 

The console show following message:

```
-[__NSArrayM objectAtIndexedSubscript:]: unrecognized selector sent to instance 0xd197fe0
```

I noticed NSArray objectAtIndexedSubscript only available in iOS 6.0 or later (https://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/NSArray.html).

Replace the line:

``` objective-c
EDAMBootstrapProfile *profile = info.profiles[0];
```

with

``` objective-c
EDAMBootstrapProfile *profile = [info.profiles objectAtIndex:0];
```

Fixes the issue.

**Comment by mustafa** [comment]
Works on iOS 5.1, closing.
