### ISSUE TITLE
Documentation is incorrect in README

### ISSUE THREAD

**Issue by dgthistle** [Evernote/evernote-sdk-ios#4]
This is no longer a valid way to initialize the session...

   // set up Evernote session singleton
    EvernoteSession *session = [[[EvernoteSession alloc] initWithHost:EVERNOTE_HOST 
                                                          consumerKey:CONSUMER_KEY 
                                                       consumerSecret:CONSUMER_SECRET] 
                          autorelease];
    [EvernoteSession setSharedSession:session];

Should be:

   // set up Evernote session singleton
    [EvernoteSession setSharedSessionHHost:EVERNOTE_HOST 
                                                          consumerKey:CONSUMER_KEY 
                                                       consumerSecret:CONSUMER_SECRET] ;

**Comment by mcglincy** [comment]
Thanks, updated!

**Comment by hermanccw** [comment]
documentation is still wrong.

should be

[EvernoteSession setSharedSessionHost:EVERNOTE_HOST 
                               consumerKey:CONSUMER_KEY 
                            consumerSecret:CONSUMER_SECRET] ;  
    }

**Comment by mcglincy** [comment]
Thanks, removed extra H typo.
