### ISSUE TITLE
Sample App not running on iPhone 6.1 simulator and device

### ISSUE THREAD

**Issue by ranjitk-plackal** [Evernote/evernote-sdk-ios#48]
Hello,

I downloaded the latest evernote sdk and was trying to run the sample app. But its not running. It builds successfully, but doesnt show on either simulator or device.

**Comment by mustafa** [comment]
Do you have the latest version of XCode? Also, did you add the consumer key and consumer secret to AppDelegat.m ? What do the logs show?

**Comment by ranjitk-plackal** [comment]
xcode version 4.6.  I have added the consumer key and consumer secret. Xcode says build succeeded.

**Comment by mustafa** [comment]
You need to select the right target (which is SampleApp) : 
![Screenshot_3_5_13_7_17_AM](https://f.cloud.github.com/assets/1184094/221768/ec38bbcc-85a7-11e2-909e-a03ec04b829d.png)

**Comment by ranjitk-plackal** [comment]
thanks mustafa
