### ISSUE TITLE
3rd party libraries should not be included in the Pod spec

### ISSUE THREAD

**Issue by alejandro-isaza** [Evernote/evernote-sdk-ios#61]
Third party libraries like SSKeychain should not be included as part of the podspec, they should be included as pod dependencies pointing to the relevan pods. Right now if your project requires SSKeychain and Evernote SDK the SSKeychain files will conflict and you will get duplicate symbol errors.

**Comment by alejandro-isaza** [comment]
Alternatively add an EN prefix to SSKeychain classes

**Comment by alejandro-isaza** [comment]
See https://github.com/CocoaPods/Specs/pull/1762

**Comment by mustafa** [comment]
We had it this way since SSKeychain did not support ARC at the time and we made our own changes to make it ARC compatible. I see that they have updated it now, so we can use a pod dependency.
