### ISSUE TITLE
It is not appropriate to make assumption about user's preferred service only using his locale

### ISSUE THREAD

**Issue by an0** [Evernote/evernote-sdk-ios#65]
This code of EvernoteSession is bad. You are making  assumption about user's preferred service just using his locale. In fact, you are subverting his's choice by forcing YinXiangBiJi on him only because he is using Chinese even thought he explicitly states that he wants to use Evernote by specifying BootstrapServerBaseURLStringUS as host. Please don't do that and let users choose their own service.

```
+ (void)setSharedSessionHost:(NSString *)host
                 consumerKey:(NSString *)consumerKey
              consumerSecret:(NSString *)consumerSecret {
    EvernoteSession *session = [self sharedSession];
    // First see if we already have a profile
    if([ENCredentialStore getCurrentProfile] == EVERNOTE_SERVICE_YINXIANG) {
        session.host = BootstrapServerBaseURLStringCN;
    }
    else if([ENCredentialStore getCurrentProfile] == EVERNOTE_SERVICE_INTERNATIONAL) {
        session.host = BootstrapServerBaseURLStringUS;
    }
    // If not, check what boostrap server you want to use based on the locale
    else if([host isEqualToString:BootstrapServerBaseURLStringUS] || [host isEqualToString:BootstrapServerBaseURLStringCN]) {
        NSString* locale = [[NSLocale currentLocale] localeIdentifier];
        if ([[locale lowercaseString] hasPrefix:kBootstrapServerBaseURLStringCN]) {
            session.host = BootstrapServerBaseURLStringCN;
        }
        else {
            session.host = BootstrapServerBaseURLStringUS;
        }
    }
    else {
        session.host = host;
    }
    session.consumerKey = consumerKey;
    session.consumerSecret = consumerSecret;
}
```

**Comment by mustafa** [comment]
It is actually not just based on locale. Based on the country, the user is allowed to switch between the two accounts. The bootstrap server identifies these rules based on a combination of locale and country (determined by IP address). More info [here](http://dev.evernote.com/documentation/cloud/chapters/bootstrap.php) .

**Comment by an0** [comment]
I read that too. It still makes too much assumption that is not totally right. Many people in China use Evernote instead of YinXiangBiJi. And there are English speaking Chinese people traveling or living outside China who use YinXiangBiJi instead of Evernote. The assumptions you are making make things difficult or event impossible, e.g., after update to the latest SDK I can no along sign in my YinXiangBiJi account because I'm using English in US.

**Comment by mustafa** [comment]
Sorry for the inconvenience. This is not related to the iOS SDK, bootstrapping protocol is part of the Evernote service. Please contact devsupport@evernote.com and we might be able to provide workarounds.

**Comment by an0** [comment]
You learned the issue but you can't feedback it to your peers? In fact, it is really easy to fix it in iOS SDK, just use the code below to replace over-smart code in SDK — why bootstrap if you already let us set service host:

```
+ (void)setSharedSessionHost:(NSString *)host
                 consumerKey:(NSString *)consumerKey
              consumerSecret:(NSString *)consumerSecret {
    EvernoteSession *session = [self sharedSession];
    session.host = host;
    session.consumerKey = consumerKey;
    session.consumerSecret = consumerSecret;
}

- (void)authenticateWithViewController:(UIViewController *)viewController
                     completionHandler:(EvernoteAuthCompletionHandler)completionHandler
{
    self.viewController = viewController;
    self.completionHandler = completionHandler;

    // authenticate is idempotent; check if we're already authenticated
    if (self.isAuthenticated) {
        [self completeAuthenticationWithError:nil];
        return;
    }

    // Do app setup sanity checks before beginning OAuth process.
    // This verification raises an NSException if problems are found.
    [self verifyConsumerKeyAndSecret];

    if (!viewController) {
        // no point continuing without a valid view controller,
        [self completeAuthenticationWithError:[NSError errorWithDomain:EvernoteSDKErrorDomain 
                                                                  code:EvernoteSDKErrorCode_NO_VIEWCONTROLLER 
                                                              userInfo:nil]];
        return;
    }

    // remove all cookies from the Evernote service so that the user can log in with
    // different credentials after declining to authorize access
    [self emptyCookieJar];

    [self startOauthAuthentication];
}
```

**Comment by AndreClaassen1** [comment]
Thank you. the (pseudo) intelligent code from Evernote bugged me today. I will fix it like you suggested.
