### ISSUE TITLE
Turn on as many compiler warning flags as possible and clean up the code

### ISSUE THREAD

**Issue by an0** [Evernote/evernote-sdk-ios#66]
The SDK code triggers too many warnings. Please turn on -Wsign-compare, -Wstrict-selector-match and -Wunknown-pragmas so you can see the issues and hopefully clean up the code.

**Comment by mustafa** [comment]
There are 0 warnings in the code with the default XCode settings. We have also added additional compiler settings. There are 0 static analysis warnings as well. Compiler warning flags are highly opinionated. Please explain why you need the one's that you have mentioned. If you need them, please fee free to open a pull request and submit for review.

**Comment by an0** [comment]
Because as an SDK, it is better to use as strict code standard as possible so that it can be easily integrated into any projects no matter how strict the coding rules they use.
