### ISSUE TITLE
Error when authenticating on device

### ISSUE THREAD

**Issue by mikaelharsjo** [Evernote/evernote-sdk-ios#69]
This works great in the simulator. But when I authenticate on my device with authenticateWithViewController I get Error saving to keychain: Error Domain=com.samsoffes.sskeychain Code=-25308 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25308.)" -25308
Error getting password from keychain: Error Domain=com.samsoffes.sskeychain Code=-25308 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25308.)". Any ideas?

**Comment by mustafa** [comment]
We haven't seen this before. Which device are you running it on?

**Comment by mikaelharsjo** [comment]
I have only tested on my iPhone5 running iOS 6.1.4. I use rubymotion for my app code but I don´t think that´s the problem. Is there anything in the provisioning profile/certificate that needs to be included?

**Comment by mustafa** [comment]
Can you try running the sample app on your device? If that does run, then it's probably a compatibility issue with rubymotion.

**Comment by mikaelharsjo** [comment]
Yes I´ll do that and let you know. Just wanted to check that I wasn´t missing anything obvious :relaxed:

**Comment by mustafa** [comment]
Closing this, please reopen if you still see the problem after removing rubymotion.
