### ISSUE TITLE
Delete Note Not work

### ISSUE THREAD

**Issue by engmohamedsalah** [Evernote/evernote-sdk-ios#71]
I tried the following code to delete note
  [[EvernoteNoteStore noteStore]deleteNoteWithGuid:noteGuid success:
                                            ^(int32_t usn){
                                                success(usn);
                                            }
                                            failure:^(NSError\* error){
                                                failure(error);
                                                NSLog(@"error=%@",error.description);
                                             }];

but it alway enter failure block and the error was 
Error Domain=com.evernote.sdk Code=1 "No information available about the error" UserInfo=0xb924d30 {NSLocalizedDescription=No information available about the error}
I sure about auth because I was able to add not.

**Comment by mustafa** [comment]
API keys do not have access to delete notes. You can move the note to the trash by marking the note as inactive.

**Comment by mustafa** [comment]
My mistake, deleteNote actually marks the note as inactive. So you should have access to it. I just tried it and its working in the iOS SDK. Make sure the guid is right. If it still does not work, please paste some sample code here about how you got the note.
