### ISSUE TITLE
Issue #32 is back?

### ISSUE THREAD

**Issue by uma-blue** [Evernote/evernote-sdk-ios#75]
Is as title.

**Comment by mustafa** [comment]
Shouldn't be. What's the issue you are facing?

**Comment by uma-blue** [comment]
I have two consumer_key.
Example, evernoteapp and evernote_app.
Use evernoteapp is no problem.
But, If use evernote_app, ending official application is started when performing authentication.

**Comment by mustafa** [comment]
Please email me your actual consumer key's. I'm not able to repro. mustafa at evernote.com

**Comment by sonsongithub** [comment]
Has been this problem fixed?
