### ISSUE TITLE
Bootstrapping for production service

### ISSUE THREAD

**Issue by waterzhang0423** [Evernote/evernote-sdk-ios#76]
1. NSString *EVERNOTE_HOST = BootstrapServerBaseURLStringUS;
2. NSString *EVERNOTE_HOST = BootstrapServerBaseURLStringCN;

How to use both US and CN service?

**Comment by mustafa** [comment]
All you need to do is make sure your consumer key is activated for both. Once that is done, the SDK will handle bootstrapping automatically based on locale and other things. For production, you can set it to BootstrapServerBaseURLStringUS or BootstrapServerBaseURLStringCN. More on bootstrapping [here](http://dev.evernote.com/doc/articles/bootstrap.php).

**Comment by waterzhang0423** [comment]
thanks.
