### ISSUE TITLE
OAuth in inline UIWebView instead of trip to Safari

### ISSUE THREAD

**Issue by VilemKurz** [Evernote/evernote-sdk-ios#8]
Authentication trip to Safari can be a source of problems, similar like SSO for Facebook (authentication trip to Safari or Facebook app). Moreover, user has to quit the app he is using. What is the roadmap? Would you consider to do authentication within the sdk in UIWebView, so that user does not need to quit the app, or this is a preparation for Single Sign On in a Facebook way?

**Comment by sethhitch** [comment]
We're considering displaying the authorization page within the SDK in a UIWebView. We haven't decided for sure yet - it's a usability / security tradeoff.

**Comment by VilemKurz** [comment]
thanks a lot for implementing this.
