### ISSUE TITLE
Production Key not working

### ISSUE THREAD

**Issue by ranjitk-plackal** [Evernote/evernote-sdk-ios#80]
Hello, 

I applied for production key, I got the mail from developer team , that it has been activated, so I tried changing the host from sandbox to production, but I get error 

Error authenticating with Evernote service: Error Domain=com.evernote.sdk Code=-3000 "The operation couldn’t be completed.

But it works with sandBox though, not understanding whats going wrong, please help

Regards
Ranjit

**Comment by mustafa** [comment]
Whats your consumer key?
